name: Restore Jest cache
description: Restore the Jest transform cache.

outputs:
  cache-hit:
    description: Whether the Jest cache was restored.
    value: ${{ steps.restore-jest-cache.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Restore Jest cache
      id: restore-jest-cache
      uses: actions/cache/restore@v4
      with:
        path: node_modules/.cache/jest
        key: jest-${{ runner.os }}-${{ hashFiles('package-lock.json', 'jest.config.js') }}
        restore-keys: |
          jest-${{ runner.os }}-
